ccflags-y += -I$(srctree)/techpack/camera-msmnile/drivers/cam_utils
ccflags-y += -I$(srctree)/techpack/camera-msmnile/drivers/cam_core
ccflags-y += -I$(srctree)/techpack/camera-msmnile/drivers/cam_cpas/include
ccflags-y += -I$(srctree)/techpack/camera-msmnile/drivers/cam_cpas

obj-$(CONFIG_SPECTRA_CAMERA) += cam_cpastop_hw.o
