ccflags-y += -I$(srctree)/techpack/camera-msmnile/drivers/cam_core
ccflags-y += -I$(srctree)/techpack/camera-msmnile/drivers/cam_cpas/include
ccflags-y += -I$(srctree)/techpack/camera-msmnile/drivers/cam_req_mgr
ccflags-y += -I$(srctree)/techpack/camera-msmnile/drivers/cam_sensor_module/cam_cci
ccflags-y += -I$(srctree)/techpack/camera-msmnile/drivers/cam_sensor_module/cam_sensor_io
ccflags-y += -I$(srctree)/techpack/camera-msmnile/drivers/cam_sensor_module/cam_sensor_utils
ccflags-y += -I$(srctree)/techpack/camera-msmnile/drivers/cam_utils

obj-$(CONFIG_SPECTRA_CAMERA) += cam_res_mgr.o
