ccflags-y += -I$(srctree)/techpack/camera-msmnile/drivers
ccflags-y += -I$(srctree)/techpack/camera-msmnile/drivers/cam_hyp_intf
ccflags-y += -I$(srctree)/techpack/camera-msmnile/drivers/cam_utils
obj-$(CONFIG_SPECTRA_CAMERA) += cam_hyp_intf.o
